# Generated by Django 5.0.1 on 2024-01-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gameid', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('dob', models.DateField()),
                ('platform', models.CharField(max_length=200)),
            ],
        ),
    ]
